language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database maker_collaboration_test;' -U postgres
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: 7e043ecc-5e9b-48ac-93ac-7990dc892a95
on:
  branch: master